services:
  dnd-atmo:
    build: .
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./public/sessions:/app/public/sessions
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped
